### ISSUE TITLE
Doesn't seem to work for me with auth

### ISSUE THREAD

**Issue by jacobalberty** [davglass/zoneminder-api#1]
I tried using this with a zm server with authentication enabled and it kept giving me 401 errors. On digging around it seems the ZMSESSID cookie gets sent twice and you should only return the latest, either need to add some dedup logic to the cookies or use a different request module that handles cookies on its own.

**Comment by jacobalberty** [comment]
I made one possible fix for this issue by using an in place of this._cookies instead of an array. This deduplicates the cookies automatically and fixed auth for me

**Comment by davglass** [comment]
Interesting, not sure why that would happen. I use this hourly on my home monitoring system that deals with 22 cameras and have never seen it issue double cookies. Send a PR and I'd happily merge it but I'd like to know what causes the double cookie issue to begin with..

**Comment by jacobalberty** [comment]
I have no idea why it is behaving like that, in theory you should get two different zmsessid's, thats normal. One pre login and one after login, in the web browser the login form only gives one zmsessid when i access it and a second when i submit, but i cant get it to give me  two on the same request so no idea?

Opening PR shortly, dunno for sure if its ideal, but it definitely assures cookies don't get duplicated
